### ISSUE TITLE
"Rubriken", "Meistgesehen" and "Sendungen A-Z" fail to load

### ISSUE THREAD

**Issue by mYnDstrEAm** [sarbes/script.module.libzdf#2]
If this is the source code for the "ZDF Mediathek" addon:

on Debian11 with Kodi19 when I click on "Rubriken" I get an error and this in the logs:

```
ProcessMouse: trying mouse action leftclick
DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.zdf_de_lite/?mode=libZdfListPage&url=https%3a%2f%2fapi.zdf.de%2fsearch%2fdocuments%3fq%3d%252A%26contentTypes%3dcategory)
DEBUG <general>:   ParentPath = [plugin://plugin.video.zdf_de_lite/]
DEBUG <general>: Thread waiting start, auto delete: false
DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.zdf_de_lite] took 31 ms
DEBUG <general>: StartScript - calling plugin ZDF Mediathek('plugin://plugin.video.zdf_de_lite/','2','?mode=libZdfListPage&url=https%3a%2f%2fapi.zdf.de%2fsearch%2fdocuments%3fq%3d%252A%26contentTypes%3dcategory','resume:false')
DEBUG <general>: Thread LanguageInvoker start, auto delete: false
 INFO <general>: initializing python engine.
DEBUG <general>: CPythonInvoker(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py): start processing
DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
DEBUG <general>: -->Python Interpreter Initialized<--
DEBUG <general>: 
                 
DEBUG <general>: CPythonInvoker(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py): the source file to load is "/home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py"
DEBUG <general>: CPythonInvoker(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py): setting the Python path to /home/username/.kodi/addons/plugin.video.zdf_de_lite:/home/username/.kodi/addons/script.module.certifi/lib:/home/username/.kodi/addons/script.module.chardet/lib:/home/username/.kodi/addons/script.module.idna/lib:/home/username/.kodi/addons/script.module.libmediathek4/lib:/home/username/.kodi/addons/script.module.libzdf/lib:/home/username/.kodi/addons/script.module.requests/lib:/home/username/.kodi/addons/script.module.urllib3/lib:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/home/username/.local/lib/python3.9/site-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages
DEBUG <general>: CPythonInvoker(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py): entering source directory /home/username/.kodi/addons/plugin.video.zdf_de_lite
DEBUG <general>: CPythonInvoker(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py): instantiating addon using automatically obtained id of "plugin.video.zdf_de_lite" dependent on version 3.0.0 of the xbmc.python api
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'KeyError'>
                 Error Contents: 'teaserImageRef'
                 Traceback (most recent call last):
                   File "/home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py", line 16, in <module>
                     o.action()
                   File "/home/username/.kodi/addons/script.module.libmediathek4/lib/libmediathek4.py", line 239, in action
                     l = self.modes[mode]()
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdf.py", line 69, in libZdfListPage
                     return self.parser.parsePage(self.params['url'])
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser.py", line 102, in parsePage
                     return self._parseSearchPage(j)
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser.py", line 141, in _parseSearchPage
                     self._grepItem(target)
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser2.py", line 32, in _grepItem
                     self._grepItemDefault(target,forcedType)
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser.py", line 194, in _grepItemDefault
                     self._grepArt(target)
                   File "/home/username/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser.py", line 262, in _grepArt
                     if 'layouts' in target['teaserImageRef']:
                 KeyError: 'teaserImageRef'
                 -->End of Python script error report<--
                 
DEBUG <general>: onExecutionDone(8, /home/username/.kodi/addons/plugin.video.zdf_de_lite/default.py)
DEBUG <general>: .
DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
 INFO <general>: Python interpreter stopped
DEBUG <general>: Thread LanguageInvoker 139800480823040 terminating
ERROR <general>: GetDirectory - Error getting plugin://plugin.video.zdf_de_lite/?mode=libZdfListPage&url=https%3a%2f%2fapi.zdf.de%2fsearch%2fdocuments%3fq%3d%252A%26contentTypes%3dcategory
DEBUG <general>: Thread waiting 139801445529344 terminating
DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zdf_de_lite/?mode=libZdfListPage&url=https%3a%2f%2fapi.zdf.de%2fsearch%2fdocuments%3fq%3d%252A%26contentTypes%3dcategory) failed
```

**Comment by bitstreamout** [comment]
I can second this. Looks like this project isn't very active or upstream does not use its self since 9 months

**Comment by tzwenn** [comment]
I fixed these issues locally at my place, enough for rare TV evenings. Feel free to include it if you find the time, until we come up with a better solution.
